# Generated by Django 4.2.2 on 2023-07-09 11:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_teacher_t_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=255)),
                ("school_year", models.CharField(max_length=20)),
                ("slug", models.SlugField(unique=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "teacher_responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "classes",
            },
        ),
    ]
